export const META_API_CALL = 'META_API_CALL';

export const TASK_DETAILS_GET = 'TASK_DETAILS_GET';
export const TASK_DETAILS_GET_SUCCESS = 'TASK_DETAILS_GET_SUCCESS';
export const TASK_DETAILS_GET_FAIL = 'TASK_DETAILS_GET_FAIL';

export const TASKS_SWITCH_CONTEXT = 'TASKS_SWITCH_CONTEXT';
export const TASKS_SWITCH_CONTEXT_SUCCESS = 'TASKS_SWITCH_CONTEXT_SUCCESS';
export const TASKS_SWITCH_CONTEXT_FAIL = 'TASKS_SWITCH_CONTEXT_FAIL';
