export const META_API_CALL = 'META_API_CALL';

export const TASK_DETAILS_GET = 'TASK_DETAILS_GET';
export const TASK_DETAILS_GET_SUCCESS = 'TASK_DETAILS_GET_SUCCESS';
export const TASK_DETAILS_GET_FAILURE = 'TASK_DETAILS_GET_FAILURE';

export const TASKS_GET = 'TASKS_GET';
export const TASKS_GET_SUCCESS = 'TASKS_GET_SUCCESS';
export const TASKS_GET_FAILURE = 'TASKS_GET_FAILURE';

export const PROJECTS_GET = 'PROJECTS_GET';
export const PROJECTS_GET_SUCCESS = 'PROJECTS_GET_SUCCESS';
export const PROJECTS_GET_FAILURE = 'PROJECTS_GET_FAILURE';

export const APPLICATION_SWITCH_CONTEXT = 'APPLICATION_SWITCH_CONTEXT';
